name: Release Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    uses: ./.github/workflows/reusable-release.yml
    with:
      dist_tag: latest
      npm_package_name: "@saiwork/saiwork"
      build_tauri: false
      release_ui: false
    secrets: inherit
