name: Release Binaries

on:
  push:
    branches:
      - saiwork

permissions:
  id-token: write
  contents: write

jobs:
  release:
    uses: ./.github/workflows/reusable-release.yml
    with:
      dist_tag: latest
      npm_package_name: "@saiwork/saiwork"
    secrets: inherit
